
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainform1.java
 *
 * Created on 22 Nov, 2011, 11:46:53 PM
 */
/**
 *
 * @author sugeerth
 */
public class mainform1 extends javax.swing.JFrame {

    public int gflag,vflag;
    public String usr, pass;
    /** Creates new form mainform1 */
    Connection con = null;
    String tcaseid, tname, taddress, tcomplaint, tdocument, ttype, twitness, tstatus, tblcaseid;

    public mainform1(int flag, String user, String passs) {
        initComponents();
        setVisible(true);
        gflag = flag;
        usr = user;
        pass = passs;
        if (gflag==1)
        {
            update.setVisible(false);
            jLabel3.setVisible(false);
        }
        try {
            //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            //System.out.println("DATABASE RECOVERY SUCCESSFULL!");
            //con = DriverManager.getConnection("jdbc:odbc:go");
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con=DriverManager.getConnection("jdbc:mysql:///go","root","");
            //Class.forName("com.mysql.jdbc.Driver").newInstance();
            //con=DriverManager.getConnection("jdbc:mysql:///go","root", "");

            if (!con.isClosed()) {
                System.out.println("Successfully connected to database");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        update = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        title.setFont(new java.awt.Font("Times New Roman", 1, 24));
        title.setText("                Welcome to AUHRMS");

        view.setLabel("VIEW");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        update.setLabel("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        logout.setActionCommand("LOGOUT");
        logout.setLabel("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel2.setText("VIEW INTERESTED :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("UPDATE DETAILS");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("LOG OUT");

        image.setIcon(new javax.swing.ImageIcon("C:\\Users\\sugeerth\\Documents\\NetBeansProjects\\dbms1\\src\\human-resources.jpg")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("DELETE");

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("VIEW DETAILS");

        jButton1.setText("VIEW DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(view, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(image)
                        .addGap(71, 71, 71))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(image))
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed

        try {
            //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            // System.out.println("DATABASE RECOVERY SUCCESSFULL!");
            // clog=DriverManager.getConnection("jdbc:odbc:go");
            // System.out.println("DATABASE RECOVERY SUCCESSFULL!");
            Statement st;
            st = con.createStatement();
            if (gflag == 0) {
                ResultSet rsLog1 = st.executeQuery("select * from applicant");
                while (rsLog1.next()) {
                    boolean b1 = rsLog1.getString(8).equals(usr);
                    boolean b2 = rsLog1.getString(9).equals(pass);
                    if (b1 && b2) {
                        //JOptionPane.showMessageDialog(null,"LOGIN SUCCESSFULL Done    \nMr."+rsLog1.getString(1)+"\nAge:          "+rsLog1.getString(2)+"\nSex:         "+rsLog1.getString(3)+"\nSkill Specialization:    "+rsLog1.getString(5)+"\n" );
                        //JOptionPane.showMessageDialog(null,"\t\t     CLICK OK \nThe Companies That have a Vacancy in your field Are:\n");
                        //Remove this line
                    
                        new empdetail(rsLog1.getInt(7));
                        setVisible(false);
                        //System.out.println("ghgfh"+rsLog1.getInt(7));
                        System.out.println("Retreiving the fields!!");

                        //flag=1;
                        break;
                    }
                }
            } else if(gflag==1){
                    System.out.println("ghgfh");
                ResultSet rsLog2 = st.executeQuery("select * from company");
                    System.out.println("ghgfh12");
                while (rsLog2.next()) {
                        System.out.println("ghgfh2131");
                    boolean b3 = rsLog2.getString(5).equals(usr);
                    boolean b4 = rsLog2.getString(6).equals(pass);
                        System.out.println("gas");
                    if (b3 && b4) {
                        try {
                            //JOptionPane.showMessageDialog(null,"LOGIN SUCCESSFULL Done    \nMr."+rsLog2.getString(1)+"\nAge:          "+rsLog2.getString(2)+"\nSex:         "+rsLog2.getString(3)+"\nSkill Specialization:    "+rsLog2.getString(5)+"\n" );
                            //JOptionPane.showMessageDialog(null,"\t\t     CLICK OK \nThe Companies That have a Vacancy in your field Are:\n");
                            //Remove this line
                              
                            new appdetail(rsLog2.getInt(4));
                            setVisible(false);
                        } catch (SQLException ex) {
                            Logger.getLogger(mainform1.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        System.out.println("Retreiving the fields!!");

                        //flag=1;
                        break;
                    }
                }
            }
          
           // jProgressBar1.setVisible(true);
        } catch (SQLException ex) {
                System.out.println("ghgfh");
            Logger.getLogger(mainform1.class.getName()).log(Level.SEVERE, null, ex);
        }






    }//GEN-LAST:event_viewActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if (gflag == 0) {

            JOptionPane.showMessageDialog(null, "update on applicants ");
            vflag=0;
            try {
                new updateform(vflag, usr, pass);
            } catch (SQLException ex) {
                System.out.println("gfhfasdasd12g");
                Logger.getLogger(mainform1.class.getName()).log(Level.SEVERE, null, ex);
            }
            setVisible(false);
        } else {
            
            JOptionPane.showMessageDialog(null, "üpdate on employers");
            

        }
    }//GEN-LAST:event_updateActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        new login();
        setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        if (gflag == 0) {
            JOptionPane.showMessageDialog(null, "delete on applicants ");
             try
            {
                PreparedStatement st;
                st=con.prepareStatement("Delete from applicant where Login='"+usr+"'");
                st.executeUpdate();
                JOptionPane.showMessageDialog(this,"The RECORD has been suceesfully deleted\nCLICK OK TO LOG OUT");
                new login();
                setVisible(false);
            }
              catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"1"+e);
            }
               
           
        }
 else{
            try
            {
            PreparedStatement st;
            st=con.prepareStatement("Delete from company where Login='"+usr+"'");
            JOptionPane.showMessageDialog(this,"The RECORD has been suceesfully deleted\nCLICK OK TO LOG OUT");
            new login();
            setVisible(false);
            }
            catch(Exception e){}
 }
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           if (gflag == 0) {

            JOptionPane.showMessageDialog(null, "VIEW DETAILS oF applicants ");
            vflag=1;
            try {
                new updateform(vflag, usr, pass);
            } catch (SQLException ex) {
                System.out.println("gfhfg");
                Logger.getLogger(mainform1.class.getName()).log(Level.SEVERE, null, ex);
            }
            setVisible(false);
        } else {

            JOptionPane.showMessageDialog(null, "update on employers");


        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new mainform1(0, null, null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel title;
    private javax.swing.JButton update;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
