

import java.sql.*;
import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * updateform.java
 *
 * Created on 23 Nov, 2011, 8:16:52 AM
 */
/**
 *
 * @author sugeerth
 */
public class updateform extends javax.swing.JFrame {

    public int gflag;
    public String usr, pass;
    /** Creates new form mainform1 */
    Connection con = null, con1 = null;
    Statement st, st1;
    String tname, sex, Education, Extra;
    int salary, age;

    /** Creates new form updateform */
    public updateform(int flag, String user, String pass1) throws SQLException {
        initComponents();
        setVisible(true);
        gflag = flag;
        usr = user;
        pass = pass1;
        if (gflag == 1) {
            System.out.println("gfhfg");
            UPDATE.setVisible(false);
            ok.setVisible(true);
           
        } else {
            System.out.println("update");
            UPDATE.setVisible(true);
            ok.setVisible(false);
        }

        try {
            //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver").newInstance();
           // con = DriverManager.getConnection("jdbc:odbc:go");
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con=DriverManager.getConnection("jdbc:mysql:///go","root","");

            //con1 = DriverManager.getConnection("jdbc:odbc:go");

            if (!con.isClosed()) {
                System.out.println("Successfully connected to database");
            }
        } catch (Exception e) {
            System.out.println("gfhfg");
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UPDATE = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        age1 = new javax.swing.JTextField();
        sex1 = new javax.swing.JTextField();
        education = new javax.swing.JTextField();
        extra = new javax.swing.JTextField();
        salary1 = new javax.swing.JTextField();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sugeerth\\Desktop\\images1.jpg")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("APPLICANT DETAILS");

        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("NAME");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("AGE");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("SEX");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("EDUCATION");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("EXTRA");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("SALARY");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        ok.setText("SHOW DETAILS");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(UPDATE)
                        .addGap(34, 34, 34)
                        .addComponent(ok)
                        .addGap(27, 27, 27)
                        .addComponent(back))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(salary1)
                            .addComponent(extra)
                            .addComponent(education)
                            .addComponent(name)
                            .addComponent(age1)
                            .addComponent(sex1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(age1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(sex1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(education, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(extra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(salary1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UPDATE)
                    .addComponent(ok)
                    .addComponent(back))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new mainform1(0, usr, pass);
        setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
       
      
        System.out.println("gfhfg");
         int j = 0;
        //String header[] = {"Name", "Age", "Sex", "Education", "Co-curriculars", "Salary"};
        System.out.println("1");
      ///  Object data[] = new String[6];
      try
      {
            Statement st3;
            System.out.println("2");
            st3 = con.createStatement();
           

            ResultSet rs2=st3.executeQuery("Select * from applicant");


            System.out.println("3");
            // for (j = 0; j <= 5; j++) {
            //         data[j] = rs1.getString(j + 1);
            //     }
            while (rs2.next()) {
                    System.out.println("3");
                  boolean b1 = rs2.getString(8).equals(usr);
                  System.out.println(usr);
                  boolean b2 = rs2.getString(9).equals(pass);
                       System.out.println(pass);
                  System.out.println("4");
                  if (b1 && b2) {
                             System.out.println("4");
                //System.out.println());
                
                name.setText(rs2.getString(1));
                 // System.out.println(rs2.getString(1));
                age1.setText(rs2.getString(2));
                sex1.setText(rs2.getString(3));
                education.setText(rs2.getString(4));
                extra.setText(rs2.getString(5));
                salary1.setText(rs2.getString(6));

               // }

            }

        }
      } catch (SQLException ex) {
             System.out.println("gfhfg");
        
        }

      
    }//GEN-LAST:event_okActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        try {
            //  Statement st;
            // st = con.createStatement();
            // ResultSet rsLog1 = st.executeQuery("select * from Applicant");
            int eflag = 0;
            int loopvar = 0;
            char ch;
            boolean bvalue;
            int count1 = 0;
            tname = this.name.getText();
            Education = this.education.getText();
            age = Integer.parseInt(this.age1.getText());
            salary = Integer.parseInt(this.salary1.getText());
            Extra = this.extra.getText();
            sex = this.sex1.getText();
            for (loopvar = 0; loopvar < tname.length(); loopvar++) {
                ch = tname.charAt(loopvar);
                if (ch >= 48 && ch <= 57) {
                    JOptionPane.showMessageDialog(this, "Please verify name field");
                    eflag = 1;
                    break;
                }
            }
            if (tname.equals("") | Education.equals("") | Extra.equals("")) {
                JOptionPane.showMessageDialog(null, "Please Fill in All Valid Entries!!");
            }
            //else

            {
                bvalue = DBupdate(tname, age, sex, Education, Extra, salary);
                con.commit();
                con.close();
            }
            //JOptionPane.showMessageDialog(null,"Update has been performed");
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(null,"Exception Enter Valid details please");
            

        }




    }//GEN-LAST:event_UPDATEActionPerformed
    public boolean DBupdate(String tname1, int age1, String sex11, String education1, String extra1, int salary1) {
        boolean retvalue = false;
        try {
            PreparedStatement st, st2;
            st = con.prepareStatement("update applicant set Name=?,Age=?,Sex=?,Education=?,Extra=?,Salary=? where Login='" + usr + "'and Pwd='" + pass + "'");
            st.setString(1, tname1);
            System.out.println(tname);
            st.setInt(2, age1);
            st.setString(3, sex11);
            st.setString(4, education1);
            st.setString(5, extra1);
            st.setInt(6, salary1);
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "applicant Details Updated!!!");
            st.executeUpdate();
            con.close();
        } catch (SQLException sQLException) {
            System.out.println("gfhfg");
            retvalue = false;
        } catch (Exception e) {
            System.out.println("gfhfg");
        }
        retvalue = true;
        return retvalue;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new updateform(0, null, null).setVisible(true);
                } catch (SQLException ex) {
                    System.out.println("gfhfg");
                    
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UPDATE;
    private javax.swing.JTextField age1;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField education;
    private javax.swing.JTextField extra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JButton ok;
    private javax.swing.JTextField salary1;
    private javax.swing.JTextField sex1;
    // End of variables declaration//GEN-END:variables
}
